### ISSUE TITLE
Problem when clearing selected items programatically

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/TwinColGridAddon#16]
According to a comment in the discussions in the addon's [Vaadin directory page](https://vaadin.com/directory/component/twincolgrid-add-on/discussions):

> Is there a way to clear the selected items programmatically. I tried with twinColGrid.setValue(null) which throws exception. Tried with twinColGrid.clear() which doesn't throw any exception, but doesn't clear the elements. I've also tried with twinColGrid.setValue(new HashSet<>()) which again, throws no exception, but doesn't clear

**Comment by javier-godoy** [comment]
The "value" of a TwinColGrid is the set of right-selected items, thus `setValue` isn't expected to modify the lists in any way. In order to clear the lists one has to call `setItems(Collections.emptyList()))`

`setValue(null)` indeeds throws an exception., which seems to be the correct behavior since `getItems()` returns an empty set when no items are selected. 

On the other hand `clear()` DOES throw an exception (as of 2.0.4-SNAPSHOT) because it's implemented as `setValue(getEmptyValue())` and `getEmptyValue()` returns null.
