### ISSUE TITLE
Drag&Drop error

### ISSUE THREAD

**Issue by fante76** [FlowingCode/TwinColGridAddon#3]
Vaadin 8.4.3
Java 1.8
Tomcat 8.5

Trying D&D I got error just moving mouse selection over left grid:

```
java.lang.NoSuchMethodError: com.vaadin.ui.components.grid.GridDragStartEvent.getDraggedItems()Ljava/util/Set;
	at com.flowingcode.vaadin.addons.twincolgrid.TwinColGrid.lambda$configDragAndDrop$7624f3f1$1(TwinColGrid.java:319)
```
get/set value of component handle Set, but method in trace handle List.

**Comment by javier-godoy** [comment]
This issue is caused by a [change in Vaadin 8.3](https://github.com/vaadin/framework/commit/6e01211931df3c294f8e3c077849c5d433c1d35f#diff-1fccb70ac45e6a0090e7a72116ca7d9d) that breaks binary compatibility (version 1.0.0 of TwinColGridAddon is compiled against Vaadin 8.1.4). We should upgrade the Vaadin dependency.
