### ISSUE TITLE
Idea: option to supply a stable item sorter

### ISSUE THREAD

**Issue by mthome** [FlowingCode/TwinColGridAddon#65]
I have a use case for keeping the items in both columns in a specified sorted order, but moving items from left to right appears to drop moved items at the end unless (manual) column sorting is on.

**Comment by mthome** [comment]
Maybe this is just a degenerate case of https://github.com/FlowingCode/TwinColGridAddon/pull/33 ?

**Comment by javier-godoy** [comment]
In any case, items will be added at the end of the internal list representation. If the grids are sorted, either manually or programmatically (which is not possible with the lastest release), dropped items will be displayed according to the configured orders.

#33 proposed an approach for programmatic sorting, but it introduced a fair share of home-made API. I think a better DX would be just exposing each grid (#69) so that sorting becomes `getRightGrid().sort(...)` (in the same way as with single Grids). #71 adds a method that configures a key for the sortable column, so that it can be retrieved with `getRightGrid().getColumnByKey()`

Would that be enough for your use case?

**Comment by javier-godoy** [comment]
I'm closing this issue because the feature is possible since version 2.2.0, as explained above.
