### ISSUE TITLE
Possibility to swap grids/sides

### ISSUE THREAD

**Issue by salitynam** [FlowingCode/TwinColGridAddon#87]
Can you please tell me if it is possible to forcibly swap the grids? While maintaining the logic of the migration buttons.
For example, to force a grid with selected items to the left instead of the right.

**Comment by javier-godoy** [comment]
Hello. 

If the component is inside of an RTL container, the grid with the selected items will be positioned to the left.
![image](https://user-images.githubusercontent.com/11554739/143250575-f631239e-c177-4021-9b88-11eefd53aef3.png)

For LTR languages, TwinColGrid is rendered as a vaadin-horizontal-layout inside of a vertical layout. You can set a `flex-direction: row-reverse` style in order to swap the grids. 

![image](https://user-images.githubusercontent.com/11554739/143249823-0e523f4a-5ac7-40e2-975e-b1c615daaff8.png)

In both cases, you will also need to rotate the buttons (since the arrow that selects items will always point to the right, regardless of dir/reverse settings)

Please let us know if you think of any addition in the API than can assist in your use case,

**Comment by salitynam** [comment]
It would be nice to be able to do this out of the box(styles of grids and buttons). And also replace the concepts of right and left grid (in favor of  available and selections for example), because in our case, as well as in the case of a vertical alignment, it is no longer relevant.

**Comment by javier-godoy** [comment]
>  And also replace the concepts/namings of "right" and "left" grid (in favor of "available" and "selections" for example), because in our case, as well as in the case of a vertical alignment, it is no longer relevant.

That's right, the left/right naming convention predates the orientation feature. I'll create a separate issue for discussing that.

**Comment by javier-godoy** [comment]
Released in v2.5.0

**Comment by salitynam** [comment]
thanks!
